// Code generated by MockGen. DO NOT EDIT.
// Source: ./mocks/router.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockSolverFactory is a mock of SolverFactory interface.
type MockSolverFactory struct {
	ctrl     *gomock.Controller
	recorder *MockSolverFactoryMockRecorder
}

// MockSolverFactoryMockRecorder is the mock recorder for MockSolverFactory.
type MockSolverFactoryMockRecorder struct {
	mock *MockSolverFactory
}

// NewMockSolverFactory creates a new mock instance.
func NewMockSolverFactory(ctrl *gomock.Controller) *MockSolverFactory {
	mock := &MockSolverFactory{ctrl: ctrl}
	mock.recorder = &MockSolverFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSolverFactory) EXPECT() *MockSolverFactoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSolverFactory) Create(eqType string) (Solver, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", eqType)
	ret0, _ := ret[0].(Solver)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockSolverFactoryMockRecorder) Create(eqType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSolverFactory)(nil).Create), eqType)
}

// MockSolver is a mock of Solver interface.
type MockSolver struct {
	ctrl     *gomock.Controller
	recorder *MockSolverMockRecorder
}

// MockSolverMockRecorder is the mock recorder for MockSolver.
type MockSolverMockRecorder struct {
	mock *MockSolver
}

// NewMockSolver creates a new mock instance.
func NewMockSolver(ctrl *gomock.Controller) *MockSolver {
	mock := &MockSolver{ctrl: ctrl}
	mock.recorder = &MockSolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSolver) EXPECT() *MockSolverMockRecorder {
	return m.recorder
}

// Solve mocks base method.
func (m *MockSolver) Solve(coeffs []float64) ([]float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Solve", coeffs)
	ret0, _ := ret[0].([]float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Solve indicates an expected call of Solve.
func (mr *MockSolverMockRecorder) Solve(coeffs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Solve", reflect.TypeOf((*MockSolver)(nil).Solve), coeffs)
}
