// Code generated by MockGen. DO NOT EDIT.
// Source: ./mocks/validating_solver.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockValidator is a mock of Validator interface.
type MockValidator struct {
	ctrl     *gomock.Controller
	recorder *MockValidatorMockRecorder
}

// MockValidatorMockRecorder is the mock recorder for MockValidator.
type MockValidatorMockRecorder struct {
	mock *MockValidator
}

// NewMockValidator creates a new mock instance.
func NewMockValidator(ctrl *gomock.Controller) *MockValidator {
	mock := &MockValidator{ctrl: ctrl}
	mock.recorder = &MockValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockValidator) EXPECT() *MockValidatorMockRecorder {
	return m.recorder
}

// ValidateCoeffs mocks base method.
func (m *MockValidator) ValidateCoeffs(a, b, c float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateCoeffs", a, b, c)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateCoeffs indicates an expected call of ValidateCoeffs.
func (mr *MockValidatorMockRecorder) ValidateCoeffs(a, b, c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateCoeffs", reflect.TypeOf((*MockValidator)(nil).ValidateCoeffs), a, b, c)
}
